// Root Gradle build for the mobi-nooa Android workspace.
//
// This wires android_mobi_nooa (the Kotlin library module) together with
// the generated mobi_nooa_bridge Flutter "add-to-app" module, per
// docs/decisions/0007-close-dart-android-bridge-gap.md.
pluginManagement {
    val flutterSdkPath: String by lazy {
        val properties = java.util.Properties()
        val localPropsFile = file("local.properties")
        if (localPropsFile.exists()) {
            localPropsFile.inputStream().use { properties.load(it) }
        }
        properties.getProperty("flutter.sdk")
            ?: System.getenv("FLUTTER_HOME")
            ?: throw GradleException(
                "flutter.sdk not set in local.properties and FLUTTER_HOME is not set. " +
                    "Copy local.properties.example to local.properties and set flutter.sdk / sdk.dir."
            )
    }

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    id("com.android.library") version "8.9.1" apply false
    id("org.jetbrains.kotlin.android") version "2.1.0" apply false
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "mobi-nooa-android"

include(":android_mobi_nooa")
include(":app")

// Includes the ":flutter" module generated by `flutter create -t module` in
// mobi_nooa_bridge/.android/, exposing mobi_nooa_bridge's compiled Dart/AOT
// code (and thus mobi_nooa_core, via its path dependency) as a Gradle
// dependency that android_mobi_nooa can consume.
apply(from = "mobi_nooa_bridge/.android/include_flutter.groovy")
